services:
  - type: web
    name: assistzap-pro
    runtime: node
    buildCommand: npm install
    startCommand: node backend/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
